import { Status } from "@/enum/enum";

export const locationFields = [
  // {
  //   name: "name",
  //   label: "Full Name",
  //   type: "text",
  //   required: true,
  // },
  // {
  //   name: "email",
  //   label: "Email",
  //   type: "text",
  //   required: true,
  // },
  {
    name: "state",
    label: "State",
    type: "select",
    options: [
        { label: "Alabama (AL)", value: "Alabama" },
        { label: "Alaska (AK)", value: "Alaska" },
        { label: "Arizona (AZ)", value: "Arizona" },
        { label: "Arkansas (AR)", value: "Arkansas" },
        { label: "California (CA)", value: "California" },
        { label: "Colorado (CO)", value: "Colorado" },
        { label: "Connecticut (CT)", value: "Connecticut" },
        { label: "Delaware (DE)", value: "Delaware" },
        { label: "District of Columbia (DC)", value: "District of Columbia" },
        { label: "Florida (FL)", value: "Florida" },
        { label: "Georgia (GA)", value: "Georgia" },
        { label: "Hawaii (HI)", value: "Hawaii" },
        { label: "Idaho (ID)", value: "Idaho" },
        { label: "Illinois (IL)", value: "Illinois" },
        { label: "Indiana (IN)", value: "Indiana" },
        { label: "Iowa (IA)", value: "Iowa" },
        { label: "Kansas (KS)", value: "Kansas" },
        { label: "Kentucky (KY)", value: "Kentucky" },
        { label: "Louisiana (LA)", value: "Louisiana" },
        { label: "Maine (ME)", value: "Maine" },
        { label: "Maryland (MD)", value: "Maryland" },
        { label: "Massachusetts (MA)", value: "Massachusetts" },
        { label: "Michigan (MI)", value: "Michigan" },
        { label: "Minnesota (MN)", value: "Minnesota" },
        { label: "Mississippi (MS)", value: "Mississippi" },
        { label: "Missouri (MO)", value: "Missouri" },
        { label: "Montana (MT)", value: "Montana" },
        { label: "Nebraska (NE)", value: "Nebraska" },
        { label: "Nevada (NV)", value: "Nevada" },
        { label: "New Hampshire (NH)", value: "New Hampshire" },
        { label: "New Jersey (NJ)", value: "New Jersey" },
        { label: "New Mexico (NM)", value: "New Mexico" },
        { label: "New York (NY)", value: "New York" },
        { label: "North Carolina (NC)", value: "North Carolina" },
        { label: "North Dakota (ND)", value: "North Dakota" },
        { label: "Ohio (OH)", value: "Ohio" },
        { label: "Oklahoma (OK)", value: "Oklahoma" },
        { label: "Oregon (OR)", value: "Oregon" },
        { label: "Pennsylvania (PA)", value: "Pennsylvania" },
        { label: "Rhode Island (RI)", value: "Rhode Island" },
        { label: "South Carolina (SC)", value: "South Carolina" },
        { label: "South Dakota (SD)", value: "South Dakota" },
        { label: "Tennessee (TN)", value: "Tennessee" },
        { label: "Texas (TX)", value: "Texas" },
        { label: "Utah (UT)", value: "Utah" },
        { label: "Vermont (VT)", value: "Vermont" },
        { label: "Virginia (VA)", value: "Virginia" },
        { label: "Washington (WA)", value: "Washington" },
        { label: "West Virginia (WV)", value: "West Virginia" },
        { label: "Wisconsin (WI)", value: "Wisconsin" },
        { label: "Wyoming (WY)", value: "Wyoming" },
    ],
    required: true,
  },
  {
  name: "city",
    label: "City",
    type: "text",
    required: true,
  },
  // {
  //   name: "address",
  //   label: "Address",
  //   type: "text",
  //   required: true,
  // },
  
  // {
  //   name: "contact_info",
  //   label: "Contact",
  //   type: "tel",
  //   required: true,
  // },
  {
    name: "status",
    label: "Status",
    type: "select",
    options: [
      { value: Status.ACTIVE, label: "Active" },
      { value: Status.INACTIVE, label: "Inactive" },
    ],
    defaultValue: Status.ACTIVE,
  },

];
